<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio property module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Property\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Rates: a property's currency, how it prices and the board bases it sells;
 * a rate per room type, season period and board basis; each period's terms.
 */
final class Version20261005000500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'property_property: currency, pricing, boards; property_rate; property_rate_terms';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE property_property ADD currency VARCHAR(3) DEFAULT NULL');
        $this->addSql("ALTER TABLE property_property ADD pricing VARCHAR(16) DEFAULT 'per_person' NOT NULL");
        $this->addSql('ALTER TABLE property_property ALTER pricing DROP DEFAULT');
        $this->addSql("ALTER TABLE property_property ADD boards JSON DEFAULT '[]' NOT NULL");
        $this->addSql('ALTER TABLE property_property ALTER boards DROP DEFAULT');

        $this->addSql(<<<'SQL'
            CREATE TABLE property_rate (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              room_type_id INT NOT NULL,
              period_id INT NOT NULL,
              board VARCHAR(16) NOT NULL,
              amount NUMERIC(10, 2) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_C0F48003296E3073 ON property_rate (room_type_id)');
        $this->addSql('CREATE INDEX IDX_C0F48003EC8B7ADE ON property_rate (period_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C0F48003296E3073EC8B7ADE58562B47 ON property_rate (room_type_id, period_id, board)');
        $this->addSql('ALTER TABLE property_rate ADD CONSTRAINT FK_RATE_ROOM FOREIGN KEY (room_type_id) REFERENCES property_room_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE property_rate ADD CONSTRAINT FK_RATE_PERIOD FOREIGN KEY (period_id) REFERENCES property_season_period (id) ON DELETE CASCADE');

        $this->addSql(<<<'SQL'
            CREATE TABLE property_rate_terms (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              period_id INT NOT NULL,
              shares JSON NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD430661EC8B7ADE ON property_rate_terms (period_id)');
        $this->addSql('ALTER TABLE property_rate_terms ADD CONSTRAINT FK_TERMS_PERIOD FOREIGN KEY (period_id) REFERENCES property_season_period (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE property_rate_terms');
        $this->addSql('DROP TABLE property_rate');
        $this->addSql('ALTER TABLE property_property DROP currency, DROP pricing, DROP boards');
    }
}
