<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio property module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Property\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Seasons, and the dated periods each runs.
 */
final class Version20261005000400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'property_season, property_season_period';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE property_season (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              property_id INT NOT NULL,
              name VARCHAR(60) NOT NULL,
              kind VARCHAR(16) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8E9334D5D17F50A6 ON property_season (uuid)');
        $this->addSql('CREATE INDEX IDX_8E9334D5549213EC ON property_season (property_id)');
        $this->addSql('ALTER TABLE property_season ADD CONSTRAINT FK_SEASON_PROPERTY FOREIGN KEY (property_id) REFERENCES property_property (id) ON DELETE CASCADE');

        $this->addSql(<<<'SQL'
            CREATE TABLE property_season_period (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              season_id INT NOT NULL,
              starts DATE NOT NULL,
              ends DATE NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C1BB0CDCD17F50A6 ON property_season_period (uuid)');
        $this->addSql('CREATE INDEX IDX_C1BB0CDC4EC001D1 ON property_season_period (season_id)');
        $this->addSql('ALTER TABLE property_season_period ADD CONSTRAINT FK_PERIOD_SEASON FOREIGN KEY (season_id) REFERENCES property_season (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE property_season_period');
        $this->addSql('DROP TABLE property_season');
    }
}
