<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio property module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Property\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Closures: nights a property sells less than it has, the whole property or
 * some units of a room type, with the reason.
 */
final class Version20261005000600 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'property_closure';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE property_closure (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              property_id INT NOT NULL,
              room_type_id INT DEFAULT NULL,
              units SMALLINT DEFAULT NULL,
              starts DATE NOT NULL,
              ends DATE NOT NULL,
              reason VARCHAR(120) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11CAC7A9D17F50A6 ON property_closure (uuid)');
        $this->addSql('CREATE INDEX IDX_11CAC7A9549213EC ON property_closure (property_id)');
        $this->addSql('CREATE INDEX IDX_11CAC7A9296E3073 ON property_closure (room_type_id)');
        $this->addSql('ALTER TABLE property_closure ADD CONSTRAINT FK_CLOSURE_PROPERTY FOREIGN KEY (property_id) REFERENCES property_property (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE property_closure ADD CONSTRAINT FK_CLOSURE_ROOM FOREIGN KEY (room_type_id) REFERENCES property_room_type (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE property_closure');
    }
}
