<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio property module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Property\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Where a person's permissions apply among the properties.
 */
final class Version20261005000800 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'property_reach';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE property_reach (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              person_id INT NOT NULL,
              reach VARCHAR(16) NOT NULL,
              properties JSON NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CB77F297217BBB47 ON property_reach (person_id)');
        $this->addSql('ALTER TABLE property_reach ADD CONSTRAINT FK_REACH_PERSON FOREIGN KEY (person_id) REFERENCES identity_user (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE property_reach');
    }
}
