<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio property module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Property\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Room types: the kinds of room a property sells, and how many of each.
 */
final class Version20261005000300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'property_room_type';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE property_room_type (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              property_id INT NOT NULL,
              name VARCHAR(80) NOT NULL,
              description TEXT DEFAULT NULL,
              sleeps SMALLINT NOT NULL,
              adults SMALLINT NOT NULL,
              count SMALLINT NOT NULL,
              features JSON NOT NULL,
              withdrawn BOOLEAN NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9E35BFF0D17F50A6 ON property_room_type (uuid)');
        $this->addSql('CREATE INDEX IDX_9E35BFF0549213EC ON property_room_type (property_id)');
        $this->addSql('ALTER TABLE property_room_type ADD CONSTRAINT FK_ROOM_TYPE_PROPERTY FOREIGN KEY (property_id) REFERENCES property_property (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE property_room_type');
    }
}
