<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio property module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Property\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Property bookings received, and their lines.
 */
final class Version20261006000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'property_booking, property_booking_line';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE property_booking (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              property_id INT NOT NULL,
              reference VARCHAR(16) NOT NULL,
              guest VARCHAR(120) NOT NULL,
              booked_by VARCHAR(120) DEFAULT NULL,
              their_reference VARCHAR(60) DEFAULT NULL,
              arrival DATE NOT NULL,
              nights SMALLINT NOT NULL,
              status VARCHAR(16) NOT NULL,
              held_until DATE DEFAULT NULL,
              notes TEXT DEFAULT NULL,
              total INT NOT NULL,
              currency VARCHAR(3) NOT NULL,
              priced_nights JSON NOT NULL,
              cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              cancellation_reason VARCHAR(200) DEFAULT NULL,
              cancellation_charge INT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B9C1A7A6AEA34913 ON property_booking (reference)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B9C1A7A6D17F50A6 ON property_booking (uuid)');
        $this->addSql('CREATE INDEX IDX_B9C1A7A6549213EC ON property_booking (property_id)');
        $this->addSql('ALTER TABLE property_booking ADD CONSTRAINT FK_BOOKING_PROPERTY FOREIGN KEY (property_id) REFERENCES property_property (id) ON DELETE CASCADE');

        $this->addSql(<<<'SQL'
            CREATE TABLE property_booking_line (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              booking_id INT NOT NULL,
              room_type_id INT NOT NULL,
              rooms SMALLINT NOT NULL,
              adults SMALLINT NOT NULL,
              children SMALLINT NOT NULL,
              infants SMALLINT NOT NULL,
              board VARCHAR(16) NOT NULL,
              amount INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_68066E13301C60 ON property_booking_line (booking_id)');
        $this->addSql('CREATE INDEX IDX_68066E1296E3073 ON property_booking_line (room_type_id)');
        $this->addSql('ALTER TABLE property_booking_line ADD CONSTRAINT FK_LINE_BOOKING FOREIGN KEY (booking_id) REFERENCES property_booking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE property_booking_line ADD CONSTRAINT FK_LINE_ROOM FOREIGN KEY (room_type_id) REFERENCES property_room_type (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE property_booking_line');
        $this->addSql('DROP TABLE property_booking');
    }
}
