<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio property module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Property\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The properties: each a camp, a lodge or a hotel, where it is, and what its
 * guests sleep in.
 */
final class Version20261004000300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'property_property';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE property_property (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(120) NOT NULL,
              location VARCHAR(160) NOT NULL,
              units INT NOT NULL,
              unit VARCHAR(16) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              uuid UUID NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D575289AD17F50A6 ON property_property (uuid)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE property_property');
    }
}
